version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: banking_postgres
    restart: always
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: accountuser
      POSTGRES_PASSWORD: accountpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
