### Создание аккаунта
POST http://localhost:8081/accounts
Content-Type: application/json

{
  "ownerName": "Аванес Иванов",
  "balance": 1000.00,
  "currency": "RUB"
}

### Получение всех аккаунтов
GET http://localhost:8081/accounts
Accept: application/json

### Пополнение счёта с id=1 на 100.00
PATCH http://localhost:8081/accounts/1/deposit?amount=100.00

### Снятие со счёта с id=1 на 100.00
PATCH http://localhost:8081/accounts/1/withdraw?amount=150.00

###  Отправляем некорректный balance (отрицательное значение)
POST http://localhost:8081/accounts
Content-Type: application/json

{
  "ownerName": "Тестовый Чел",
  "balance": null,
  "currency": "RUB"
}

### перевод со счета на счет
PATCH http://localhost:8081/accounts/transfer?fromAccountId=1&toAccountId=2&amount=100.00
