server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: accountuser
    password: accountpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #validate # ❗ Проверка, но не создание таблиц// update # В разработке ок, но для продакшна лучше использовать validate или none
    show-sql: true
    open-in-view: false  # Это важно для REST API: отключает открытое соединение в слое представления

  flyway:
    enabled: true
    locations: classpath:db/migration

    schemas: account_schema
    default-schema: account_schema






